using backend.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501090000_AddStockTables")]
    public partial class AddStockTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "StockItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Sku" character varying(100) NULL,
    "Unit" character varying(20) NOT NULL,
    "Description" character varying(500) NULL,
    "ReorderLevel" numeric(18,2) NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StockItems" PRIMARY KEY ("Id")
);
""");

                migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "StockMovements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StockItemId" integer NOT NULL,
    "QuantityChange" numeric(18,2) NOT NULL,
    "MovementKind" character varying(50) NULL,
    "Note" character varying(500) NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StockMovements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockMovements_StockItems_StockItemId" FOREIGN KEY ("StockItemId") REFERENCES "StockItems" ("Id") ON DELETE CASCADE
);
""");

                migrationBuilder.Sql("""
CREATE INDEX IF NOT EXISTS "IX_StockMovements_StockItemId" ON "StockMovements" ("StockItemId");
""");

                return;
            }

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "StockItems" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_StockItems" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "Sku" TEXT NULL,
    "Unit" TEXT NOT NULL,
    "Description" TEXT NULL,
    "ReorderLevel" TEXT NULL,
    "CreatedAt" TEXT NOT NULL
);
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "StockMovements" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_StockMovements" PRIMARY KEY AUTOINCREMENT,
    "StockItemId" INTEGER NOT NULL,
    "QuantityChange" TEXT NOT NULL,
    "MovementKind" TEXT NULL,
    "Note" TEXT NULL,
    "OccurredAt" TEXT NOT NULL,
    CONSTRAINT "FK_StockMovements_StockItems_StockItemId" FOREIGN KEY ("StockItemId") REFERENCES "StockItems" ("Id") ON DELETE CASCADE
);
""");

            migrationBuilder.Sql("""
CREATE INDEX IF NOT EXISTS "IX_StockMovements_StockItemId" ON "StockMovements" ("StockItemId");
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "StockMovements");

            migrationBuilder.DropTable(
                name: "StockItems");
        }
    }
}
