using backend.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509090000_AddInvoiceStockDeductions")]
    public partial class AddInvoiceStockDeductions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "InvoiceStockDeductions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DeductionKey" character varying(200) NOT NULL,
    "InvoiceNumber" character varying(100) NOT NULL,
    "CustomerName" character varying(200) NULL,
    "AppliedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InvoiceStockDeductions" PRIMARY KEY ("Id")
);
""");

                migrationBuilder.Sql("""
CREATE UNIQUE INDEX IF NOT EXISTS "IX_InvoiceStockDeductions_DeductionKey"
ON "InvoiceStockDeductions" ("DeductionKey");
""");

                return;
            }

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "InvoiceStockDeductions" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_InvoiceStockDeductions" PRIMARY KEY AUTOINCREMENT,
    "DeductionKey" TEXT NOT NULL,
    "InvoiceNumber" TEXT NOT NULL,
    "CustomerName" TEXT NULL,
    "AppliedAt" TEXT NOT NULL
);
""");

            migrationBuilder.Sql("""
CREATE UNIQUE INDEX IF NOT EXISTS "IX_InvoiceStockDeductions_DeductionKey"
ON "InvoiceStockDeductions" ("DeductionKey");
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "InvoiceStockDeductions");
        }
    }
}
