using backend.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502090000_AddWorkerTasks")]
    public partial class AddWorkerTasks : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "WorkerTasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "Deadline" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "AssignedUserId" integer NOT NULL,
    "CreatedById" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_WorkerTasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkerTasks_Users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkerTasks_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

                migrationBuilder.Sql("""
CREATE INDEX IF NOT EXISTS "IX_WorkerTasks_AssignedUserId" ON "WorkerTasks" ("AssignedUserId");
""");

                migrationBuilder.Sql("""
CREATE INDEX IF NOT EXISTS "IX_WorkerTasks_CreatedById" ON "WorkerTasks" ("CreatedById");
""");

                return;
            }

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "WorkerTasks" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_WorkerTasks" PRIMARY KEY AUTOINCREMENT,
    "Title" TEXT NOT NULL,
    "Description" TEXT NOT NULL,
    "Deadline" TEXT NOT NULL,
    "Status" TEXT NOT NULL,
    "AssignedUserId" INTEGER NOT NULL,
    "CreatedById" INTEGER NOT NULL,
    "CreatedAt" TEXT NOT NULL,
    "UpdatedAt" TEXT NULL,
    CONSTRAINT "FK_WorkerTasks_Users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkerTasks_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            migrationBuilder.Sql("""
CREATE INDEX IF NOT EXISTS "IX_WorkerTasks_AssignedUserId" ON "WorkerTasks" ("AssignedUserId");
""");

            migrationBuilder.Sql("""
CREATE INDEX IF NOT EXISTS "IX_WorkerTasks_CreatedById" ON "WorkerTasks" ("CreatedById");
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "WorkerTasks");
        }
    }
}
