using Microsoft.EntityFrameworkCore;

namespace backend.Data
{
    /// <summary>
    /// Ensures fiscal receipt tables exist when production databases predate the feature.
    /// </summary>
    public static class FiscalReceiptSchemaBootstrapper
    {
        public static async Task EnsureAsync(ApplicationDbContext db)
        {
            if (db.Database.IsNpgsql())
            {
                await EnsurePostgresAsync(db);
                return;
            }

            if (db.Database.IsSqlite())
            {
                await EnsureSqliteAsync(db);
            }
        }

        private static async Task EnsurePostgresAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "FiscalReceipts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReceiptNumber" character varying(100) NOT NULL,
    "ClientRequestId" character varying(100) NULL,
    "CustomerName" character varying(200) NULL,
    "CustomerPhone" character varying(50) NULL,
    "ItemsJson" text NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "Notes" character varying(1000) NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "PrintedAt" timestamp with time zone NULL,
    "ArchivedAt" timestamp with time zone NULL,
    "CreatedById" integer NOT NULL,
    CONSTRAINT "PK_FiscalReceipts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FiscalReceipts_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "FiscalReceiptArchives" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FiscalReceiptId" integer NULL,
    "ReceiptNumber" character varying(100) NOT NULL,
    "ClientRequestId" character varying(100) NULL,
    "CustomerName" character varying(200) NULL,
    "CustomerPhone" character varying(50) NULL,
    "ItemsJson" text NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "Notes" character varying(1000) NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "PrintedAt" timestamp with time zone NOT NULL,
    "ArchivedAt" timestamp with time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    CONSTRAINT "PK_FiscalReceiptArchives" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FiscalReceiptArchives_FiscalReceipts_FiscalReceiptId" FOREIGN KEY ("FiscalReceiptId") REFERENCES "FiscalReceipts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FiscalReceiptArchives_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "FiscalReceiptStockDeductions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DeductionKey" character varying(200) NOT NULL,
    "ReceiptNumber" character varying(100) NOT NULL,
    "CustomerName" character varying(200) NULL,
    "AppliedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FiscalReceiptStockDeductions" PRIMARY KEY ("Id")
);
""");

            foreach (var statement in IndexStatements)
            {
                await db.Database.ExecuteSqlRawAsync(statement);
            }
        }

        private static async Task EnsureSqliteAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "FiscalReceipts" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_FiscalReceipts" PRIMARY KEY AUTOINCREMENT,
    "ReceiptNumber" TEXT NOT NULL,
    "ClientRequestId" TEXT NULL,
    "CustomerName" TEXT NULL,
    "CustomerPhone" TEXT NULL,
    "ItemsJson" TEXT NOT NULL,
    "Subtotal" TEXT NOT NULL,
    "Total" TEXT NOT NULL,
    "Notes" TEXT NULL,
    "Status" TEXT NOT NULL,
    "CreatedAt" TEXT NOT NULL,
    "PrintedAt" TEXT NULL,
    "ArchivedAt" TEXT NULL,
    "CreatedById" INTEGER NOT NULL,
    CONSTRAINT "FK_FiscalReceipts_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "FiscalReceiptArchives" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_FiscalReceiptArchives" PRIMARY KEY AUTOINCREMENT,
    "FiscalReceiptId" INTEGER NULL,
    "ReceiptNumber" TEXT NOT NULL,
    "ClientRequestId" TEXT NULL,
    "CustomerName" TEXT NULL,
    "CustomerPhone" TEXT NULL,
    "ItemsJson" TEXT NOT NULL,
    "Subtotal" TEXT NOT NULL,
    "Total" TEXT NOT NULL,
    "Notes" TEXT NULL,
    "CreatedAt" TEXT NOT NULL,
    "PrintedAt" TEXT NOT NULL,
    "ArchivedAt" TEXT NOT NULL,
    "CreatedById" INTEGER NOT NULL,
    CONSTRAINT "FK_FiscalReceiptArchives_FiscalReceipts_FiscalReceiptId" FOREIGN KEY ("FiscalReceiptId") REFERENCES "FiscalReceipts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FiscalReceiptArchives_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "FiscalReceiptStockDeductions" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_FiscalReceiptStockDeductions" PRIMARY KEY AUTOINCREMENT,
    "DeductionKey" TEXT NOT NULL,
    "ReceiptNumber" TEXT NOT NULL,
    "CustomerName" TEXT NULL,
    "AppliedAt" TEXT NOT NULL
);
""");

            foreach (var statement in IndexStatements)
            {
                await db.Database.ExecuteSqlRawAsync(statement);
            }
        }

        private static readonly string[] IndexStatements =
        {
            @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FiscalReceipts_ReceiptNumber"" ON ""FiscalReceipts"" (""ReceiptNumber"");",
            @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FiscalReceipts_ClientRequestId"" ON ""FiscalReceipts"" (""ClientRequestId"") WHERE ""ClientRequestId"" IS NOT NULL;",
            @"CREATE INDEX IF NOT EXISTS ""IX_FiscalReceipts_Status"" ON ""FiscalReceipts"" (""Status"");",
            @"CREATE INDEX IF NOT EXISTS ""IX_FiscalReceipts_CreatedAt"" ON ""FiscalReceipts"" (""CreatedAt"");",
            @"CREATE INDEX IF NOT EXISTS ""IX_FiscalReceipts_PrintedAt"" ON ""FiscalReceipts"" (""PrintedAt"");",
            @"CREATE INDEX IF NOT EXISTS ""IX_FiscalReceipts_CreatedById"" ON ""FiscalReceipts"" (""CreatedById"");",
            @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FiscalReceiptArchives_FiscalReceiptId"" ON ""FiscalReceiptArchives"" (""FiscalReceiptId"") WHERE ""FiscalReceiptId"" IS NOT NULL;",
            @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FiscalReceiptArchives_ReceiptNumber"" ON ""FiscalReceiptArchives"" (""ReceiptNumber"");",
            @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FiscalReceiptArchives_ClientRequestId"" ON ""FiscalReceiptArchives"" (""ClientRequestId"") WHERE ""ClientRequestId"" IS NOT NULL;",
            @"CREATE INDEX IF NOT EXISTS ""IX_FiscalReceiptArchives_CreatedAt"" ON ""FiscalReceiptArchives"" (""CreatedAt"");",
            @"CREATE INDEX IF NOT EXISTS ""IX_FiscalReceiptArchives_PrintedAt"" ON ""FiscalReceiptArchives"" (""PrintedAt"");",
            @"CREATE INDEX IF NOT EXISTS ""IX_FiscalReceiptArchives_ArchivedAt"" ON ""FiscalReceiptArchives"" (""ArchivedAt"");",
            @"CREATE INDEX IF NOT EXISTS ""IX_FiscalReceiptArchives_CreatedById"" ON ""FiscalReceiptArchives"" (""CreatedById"");",
            @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FiscalReceiptStockDeductions_DeductionKey"" ON ""FiscalReceiptStockDeductions"" (""DeductionKey"");",
            @"CREATE INDEX IF NOT EXISTS ""IX_FiscalReceiptStockDeductions_ReceiptNumber"" ON ""FiscalReceiptStockDeductions"" (""ReceiptNumber"");",
            @"CREATE INDEX IF NOT EXISTS ""IX_FiscalReceiptStockDeductions_AppliedAt"" ON ""FiscalReceiptStockDeductions"" (""AppliedAt"");"
        };
    }
}
