using System.Data;
using Microsoft.EntityFrameworkCore;

namespace backend.Data
{
    /// <summary>
    /// Ensures invoice archive tables exist when production databases predate the feature.
    /// </summary>
    public static class InvoiceArchiveSchemaBootstrapper
    {
        public static async Task EnsureAsync(ApplicationDbContext db)
        {
            if (db.Database.IsNpgsql())
            {
                await EnsurePostgresAsync(db);
                return;
            }

            if (db.Database.IsSqlite())
            {
                await EnsureSqliteAsync(db);
            }
        }

        private static async Task EnsurePostgresAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "InvoiceArchives" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceNumber" character varying(100) NOT NULL,
    "ClientRequestId" character varying(100) NULL,
    "CustomerName" character varying(200) NOT NULL,
    "CustomerAddress" character varying(500) NULL,
    "CustomerPhone" character varying(50) NULL,
    "Language" text NOT NULL,
    "ItemsJson" text NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "Notes" character varying(1000) NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    CONSTRAINT "PK_InvoiceArchives" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceArchives_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync("""
ALTER TABLE "InvoiceArchives"
ADD COLUMN IF NOT EXISTS "ClientRequestId" character varying(100) NULL;
""");

            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_CreatedAt"" ON ""InvoiceArchives"" (""CreatedAt"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_CreatedById"" ON ""InvoiceArchives"" (""CreatedById"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_InvoiceNumber"" ON ""InvoiceArchives"" (""InvoiceNumber"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_InvoiceArchives_ClientRequestId"" ON ""InvoiceArchives"" (""ClientRequestId"") WHERE ""ClientRequestId"" IS NOT NULL;");
        }

        private static async Task EnsureSqliteAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "InvoiceArchives" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_InvoiceArchives" PRIMARY KEY AUTOINCREMENT,
    "InvoiceNumber" TEXT NOT NULL,
    "ClientRequestId" TEXT NULL,
    "CustomerName" TEXT NOT NULL,
    "CustomerAddress" TEXT NULL,
    "CustomerPhone" TEXT NULL,
    "Language" TEXT NOT NULL,
    "ItemsJson" TEXT NOT NULL,
    "Subtotal" TEXT NOT NULL,
    "Total" TEXT NOT NULL,
    "Notes" TEXT NULL,
    "CreatedAt" TEXT NOT NULL,
    "CreatedById" INTEGER NOT NULL,
    CONSTRAINT "FK_InvoiceArchives_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            if (!await SqliteColumnExistsAsync(db, "InvoiceArchives", "ClientRequestId"))
            {
                await db.Database.ExecuteSqlRawAsync(
                    @"ALTER TABLE ""InvoiceArchives"" ADD COLUMN ""ClientRequestId"" TEXT NULL;");
            }

            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_CreatedAt"" ON ""InvoiceArchives"" (""CreatedAt"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_CreatedById"" ON ""InvoiceArchives"" (""CreatedById"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_InvoiceNumber"" ON ""InvoiceArchives"" (""InvoiceNumber"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_InvoiceArchives_ClientRequestId"" ON ""InvoiceArchives"" (""ClientRequestId"") WHERE ""ClientRequestId"" IS NOT NULL;");
        }

        private static async Task<bool> SqliteColumnExistsAsync(
            ApplicationDbContext db,
            string tableName,
            string columnName)
        {
            var connection = db.Database.GetDbConnection();
            var shouldClose = connection.State != ConnectionState.Open;
            if (shouldClose)
            {
                await db.Database.OpenConnectionAsync();
            }

            try
            {
                await using var command = connection.CreateCommand();
                command.CommandText = $@"PRAGMA table_info(""{tableName}"");";

                await using var reader = await command.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    if (string.Equals(reader["name"]?.ToString(), columnName, StringComparison.OrdinalIgnoreCase))
                    {
                        return true;
                    }
                }

                return false;
            }
            finally
            {
                if (shouldClose)
                {
                    await db.Database.CloseConnectionAsync();
                }
            }
        }
    }
}
