using Microsoft.EntityFrameworkCore;

namespace backend.Data
{
    /// <summary>
    /// Ensures invoice archive tables exist when production databases predate the feature.
    /// </summary>
    public static class InvoiceArchiveSchemaBootstrapper
    {
        public static async Task EnsureAsync(ApplicationDbContext db)
        {
            if (db.Database.IsNpgsql())
            {
                await EnsurePostgresAsync(db);
                return;
            }

            if (db.Database.IsSqlite())
            {
                await EnsureSqliteAsync(db);
            }
        }

        private static async Task EnsurePostgresAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "InvoiceArchives" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceNumber" character varying(100) NOT NULL,
    "CustomerName" character varying(200) NOT NULL,
    "CustomerAddress" character varying(500) NULL,
    "CustomerPhone" character varying(50) NULL,
    "Language" text NOT NULL,
    "ItemsJson" text NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "Notes" character varying(1000) NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    CONSTRAINT "PK_InvoiceArchives" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceArchives_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_CreatedAt"" ON ""InvoiceArchives"" (""CreatedAt"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_CreatedById"" ON ""InvoiceArchives"" (""CreatedById"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_InvoiceNumber"" ON ""InvoiceArchives"" (""InvoiceNumber"");");
        }

        private static async Task EnsureSqliteAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "InvoiceArchives" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_InvoiceArchives" PRIMARY KEY AUTOINCREMENT,
    "InvoiceNumber" TEXT NOT NULL,
    "CustomerName" TEXT NOT NULL,
    "CustomerAddress" TEXT NULL,
    "CustomerPhone" TEXT NULL,
    "Language" TEXT NOT NULL,
    "ItemsJson" TEXT NOT NULL,
    "Subtotal" TEXT NOT NULL,
    "Total" TEXT NOT NULL,
    "Notes" TEXT NULL,
    "CreatedAt" TEXT NOT NULL,
    "CreatedById" INTEGER NOT NULL,
    CONSTRAINT "FK_InvoiceArchives_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_CreatedAt"" ON ""InvoiceArchives"" (""CreatedAt"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_CreatedById"" ON ""InvoiceArchives"" (""CreatedById"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_InvoiceArchives_InvoiceNumber"" ON ""InvoiceArchives"" (""InvoiceNumber"");");
        }
    }
}
