using Microsoft.EntityFrameworkCore;

namespace backend.Data
{
    /// <summary>
    /// Ensures stock tables and compatible stock columns exist on older databases.
    /// </summary>
    public static class StockSchemaBootstrapper
    {
        public static async Task EnsureAsync(ApplicationDbContext db)
        {
            if (db.Database.IsNpgsql())
            {
                await EnsurePostgresAsync(db);
                return;
            }

            if (db.Database.IsSqlite())
            {
                await EnsureSqliteAsync(db);
            }
        }

        private static async Task EnsurePostgresAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "StockItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Sku" character varying(100) NULL,
    "Unit" character varying(20) NOT NULL,
    "StockType" character varying(20) NOT NULL DEFAULT 'Material',
    "Description" character varying(500) NULL,
    "ReorderLevel" numeric(18,2) NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StockItems" PRIMARY KEY ("Id")
);
""");

            await db.Database.ExecuteSqlRawAsync("""
ALTER TABLE "StockItems"
ADD COLUMN IF NOT EXISTS "StockType" character varying(20) NOT NULL DEFAULT 'Material';
""");

            await db.Database.ExecuteSqlRawAsync("""
UPDATE "StockItems"
SET "StockType" = 'Material'
WHERE "StockType" IS NULL;
""");

            await db.Database.ExecuteSqlRawAsync("""
ALTER TABLE "StockItems" ALTER COLUMN "StockType" SET DEFAULT 'Material';
ALTER TABLE "StockItems" ALTER COLUMN "StockType" SET NOT NULL;
""");

            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "StockMovements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StockItemId" integer NOT NULL,
    "QuantityChange" numeric(18,2) NOT NULL,
    "MovementKind" character varying(50) NULL,
    "Note" character varying(500) NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StockMovements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockMovements_StockItems_StockItemId" FOREIGN KEY ("StockItemId") REFERENCES "StockItems" ("Id") ON DELETE CASCADE
);
""");

            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_StockMovements_StockItemId"" ON ""StockMovements"" (""StockItemId"");");

            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "InvoiceStockDeductions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DeductionKey" character varying(200) NOT NULL,
    "InvoiceNumber" character varying(100) NOT NULL,
    "CustomerName" character varying(200) NULL,
    "AppliedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InvoiceStockDeductions" PRIMARY KEY ("Id")
);
""");

            await db.Database.ExecuteSqlRawAsync(
                @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_InvoiceStockDeductions_DeductionKey"" ON ""InvoiceStockDeductions"" (""DeductionKey"");");
        }

        private static async Task EnsureSqliteAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""StockItems"" (
    ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_StockItems"" PRIMARY KEY AUTOINCREMENT,
    ""Name"" TEXT NOT NULL,
    ""Sku"" TEXT NULL,
    ""Unit"" TEXT NOT NULL,
    ""StockType"" TEXT NOT NULL DEFAULT 'Material',
    ""Description"" TEXT NULL,
    ""ReorderLevel"" TEXT NULL,
    ""CreatedAt"" TEXT NOT NULL
);
");
            if (!await SqliteColumnExistsAsync(db, "StockItems", "StockType"))
            {
                await db.Database.ExecuteSqlRawAsync(
                    @"ALTER TABLE ""StockItems"" ADD COLUMN ""StockType"" TEXT NOT NULL DEFAULT 'Material';");
            }

            await db.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""StockMovements"" (
    ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_StockMovements"" PRIMARY KEY AUTOINCREMENT,
    ""StockItemId"" INTEGER NOT NULL,
    ""QuantityChange"" TEXT NOT NULL,
    ""MovementKind"" TEXT NULL,
    ""Note"" TEXT NULL,
    ""OccurredAt"" TEXT NOT NULL,
    CONSTRAINT ""FK_StockMovements_StockItems_StockItemId"" FOREIGN KEY (""StockItemId"") REFERENCES ""StockItems"" (""Id"") ON DELETE CASCADE
);
");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_StockMovements_StockItemId"" ON ""StockMovements"" (""StockItemId"");");

            await db.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""InvoiceStockDeductions"" (
    ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_InvoiceStockDeductions"" PRIMARY KEY AUTOINCREMENT,
    ""DeductionKey"" TEXT NOT NULL,
    ""InvoiceNumber"" TEXT NOT NULL,
    ""CustomerName"" TEXT NULL,
    ""AppliedAt"" TEXT NOT NULL
);
");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_InvoiceStockDeductions_DeductionKey"" ON ""InvoiceStockDeductions"" (""DeductionKey"");");
        }

        private static async Task<bool> SqliteColumnExistsAsync(
            ApplicationDbContext db,
            string tableName,
            string columnName)
        {
            var connection = db.Database.GetDbConnection();
            var shouldClose = connection.State == System.Data.ConnectionState.Closed;

            if (shouldClose)
            {
                await db.Database.OpenConnectionAsync();
            }

            try
            {
                await using var command = connection.CreateCommand();
                var escapedTableName = tableName.Replace("\"", "\"\"", StringComparison.Ordinal);
                command.CommandText = $@"PRAGMA table_info(""{escapedTableName}"");";

                await using var reader = await command.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    if (string.Equals(reader.GetString(1), columnName, StringComparison.Ordinal))
                    {
                        return true;
                    }
                }

                return false;
            }
            finally
            {
                if (shouldClose && connection.State != System.Data.ConnectionState.Closed)
                {
                    await db.Database.CloseConnectionAsync();
                }
            }
        }
    }
}
