using Microsoft.EntityFrameworkCore;

namespace backend.Data
{
    /// <summary>
    /// Ensures worker task tables exist when production databases predate the worker task feature.
    /// </summary>
    public static class WorkerTaskSchemaBootstrapper
    {
        public static async Task EnsureAsync(ApplicationDbContext db)
        {
            if (db.Database.IsNpgsql())
            {
                await EnsurePostgresAsync(db);
                return;
            }

            if (db.Database.IsSqlite())
            {
                await EnsureSqliteAsync(db);
            }
        }

        private static async Task EnsurePostgresAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "WorkerTasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "Deadline" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "AssignedUserId" integer NOT NULL,
    "CreatedById" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_WorkerTasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkerTasks_Users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkerTasks_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_WorkerTasks_AssignedUserId"" ON ""WorkerTasks"" (""AssignedUserId"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_WorkerTasks_CreatedById"" ON ""WorkerTasks"" (""CreatedById"");");
        }

        private static async Task EnsureSqliteAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "WorkerTasks" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_WorkerTasks" PRIMARY KEY AUTOINCREMENT,
    "Title" TEXT NOT NULL,
    "Description" TEXT NOT NULL,
    "Deadline" TEXT NOT NULL,
    "Status" TEXT NOT NULL,
    "AssignedUserId" INTEGER NOT NULL,
    "CreatedById" INTEGER NOT NULL,
    "CreatedAt" TEXT NOT NULL,
    "UpdatedAt" TEXT NULL,
    CONSTRAINT "FK_WorkerTasks_Users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkerTasks_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_WorkerTasks_AssignedUserId"" ON ""WorkerTasks"" (""AssignedUserId"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_WorkerTasks_CreatedById"" ON ""WorkerTasks"" (""CreatedById"");");
        }
    }
}
