using Microsoft.EntityFrameworkCore;

namespace backend.Data
{
    /// <summary>
    /// Ensures work sales tables exist when production databases predate the feature.
    /// </summary>
    public static class WorkSaleSchemaBootstrapper
    {
        public static async Task EnsureAsync(ApplicationDbContext db)
        {
            if (db.Database.IsNpgsql())
            {
                await EnsurePostgresAsync(db);
                return;
            }

            if (db.Database.IsSqlite())
            {
                await EnsureSqliteAsync(db);
            }
        }

        private static async Task EnsurePostgresAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "WorkSales" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkName" character varying(200) NOT NULL,
    "TotalWorkM2" numeric(18,2) NOT NULL,
    "ClientPricePerM2" numeric(18,2) NOT NULL,
    "SubcontractorPricePerM2" numeric(18,2) NOT NULL,
    "TotalRevenue" numeric(18,2) NOT NULL,
    "TotalCost" numeric(18,2) NOT NULL,
    "Profit" numeric(18,2) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Notes" character varying(1000) NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "CreatedById" integer NOT NULL,
    CONSTRAINT "PK_WorkSales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkSales_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_WorkSales_CreatedById"" ON ""WorkSales"" (""CreatedById"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_WorkSales_Date"" ON ""WorkSales"" (""Date"");");
        }

        private static async Task EnsureSqliteAsync(ApplicationDbContext db)
        {
            await db.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "WorkSales" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_WorkSales" PRIMARY KEY AUTOINCREMENT,
    "WorkName" TEXT NOT NULL,
    "TotalWorkM2" TEXT NOT NULL,
    "ClientPricePerM2" TEXT NOT NULL,
    "SubcontractorPricePerM2" TEXT NOT NULL,
    "TotalRevenue" TEXT NOT NULL,
    "TotalCost" TEXT NOT NULL,
    "Profit" TEXT NOT NULL,
    "Date" TEXT NOT NULL,
    "Notes" TEXT NULL,
    "CreatedAt" TEXT NOT NULL,
    "UpdatedAt" TEXT NULL,
    "CreatedById" INTEGER NOT NULL,
    CONSTRAINT "FK_WorkSales_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
""");

            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_WorkSales_CreatedById"" ON ""WorkSales"" (""CreatedById"");");
            await db.Database.ExecuteSqlRawAsync(
                @"CREATE INDEX IF NOT EXISTS ""IX_WorkSales_Date"" ON ""WorkSales"" (""Date"");");
        }
    }
}
